if(process.env.NODE_ENV !== 'production'){
    require('dotenv').config()
}
const express= require('express')
const app = express()
const methodOverride = require('method-override')
const mongoose = require('mongoose')
mongoose.connect('mongodb://localhost/library_db',()=>{
    console.log('server connected')
})
const expresslayouts = require('express-ejs-layouts')
const userRouter = require('./routes/index')
const authorRouter = require('./routes/authors')
const bookRouter = require('./routes/books')
app.use(express.urlencoded({extended:false}))
app.set('view engine','ejs')
app.set('views',__dirname+'/views')
app.set('layout','layouts/layout')
app.use(expresslayouts)
app.use(methodOverride('_method'))
app.use(express.static('public'))
app.use('/',userRouter)
app.use('/authors',authorRouter)
app.use('/books',bookRouter)
app.listen(3000)
